name: human_resources
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  postgres: ^3.0.1

  flutter_svg: ^1.1.4

  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/Domine-Bold.ttf
          weight: 700
        - asset: assets/fonts/Domine-Medium.ttf
        - asset: assets/fonts/Domine-Regular.ttf
        - asset: assets/fonts/Domine-SemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
